name: 🚀 Upload artifacts to AWS S3
run-name: Upload artifacts to AWS S3

on: workflow_dispatch
  #release:
   # types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get artifacts associated with current commit
        run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/$OWNER/$REPO/actions/artifacts?name=webapp-artifacts-$COMMIT_SHA

          echo 'ARTIFACT_ID='$artifactId >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ github.token }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          COMMIT_SHA: ${{ github.sha }}

      - name: Download artifacts
        run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/$OWNER/$REPO/actions/artifacts/$ARTIFACT_ID/zip
        env:
          GH_TOKEN: ${{ github.token }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload to S3
        run: |
          aws s3 cp . s3://${{ secrets.AWS_S3_BUCKET }}/ --recursive