name: Upload artifacts to AWS S3

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          run-id: 13728569619
          github-token: ${{ secrets.GH_PAT }}
          repository: VitaliiKhmelko/playground
          path: 13728569619
          # Name of the artifact to download.
          # name: webapp-artifacts

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload to S3
        run: |
          aws s3 cp . s3://${{ secrets.AWS_S3_BUCKET }}/ --recursive